
def x():
    print(nice)

try:
    print(x)
except:
    print("An exception occured")
